{% set name = "pytim" %}
{% set version = "1.0.5" %}
{% set sha256 = "36fe2fd4c85aef4c1896f76d9493fe3ac32f7a08032146d4af3b774815531f99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [py2k or win or python_impl == 'pypy' or py<310]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - setuptools
    - cython >=3.0.8
    - scipy >=1.1.0
    - numpy >=2.13
  run:
    - python
    - numpy >=2.13
    - scipy >=1.12.0
    - scikit-image >=0.24.0
    - gsd >3.0.0
    - {{ pin_compatible('numpy') }}
    - mdanalysis >=2.8.0
    - pywavelets >=1.8.0

test:
  imports:
    - MDAnalysis
    - pytim
    - pytim.datafiles

about:
  home: http://github.com/Marcello-Sega/pytim
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: A python based tool for interfacial molecules analysis
  description: |
    Pytim provides a set of tools for interfacial analysis in molecular simulations.
    Most major configuration and trajectory formats can be read, thanks to MDAnalysis.
  doc_url: https://marcello-sega.github.io/pytim/
  dev_url: https://github.com/Marcello-Sega/pytim

extra:
  recipe-maintainers:
    - Marcello-Sega
