travis:
  secure:
    BINSTAR_TOKEN: UaIsvUYvQdKjH+wlZM6jgw1vk2zhLn7in1+9Tge21GFQ/ZY7rnkIprA4PZi3mK+7vsMKBQmO3zIg73qFmhyMDdJmcQeSAbaAcuCPd7IJdO54wk2dlewCKGgttXMITcAxl1+NxBREy+S77stxd3+KNVT82fPyT6LdAjeh9gLqNA+KEeuub1vSUWMt+yoATnZkRB9RNJTVKhMyMuG5jAh1TLfRXgGJFVw54FyRT9FQz6Emw8Tda1UyqZTH6oVC9EqZE6BKI5bfeOQ8SX6tdmNrxI36TOmA+jCYVehGSrRG6WZwB/49mpeANfxo9sRfXFRVdAd1P9YXNl0iPKc/86+ZRXUbe4s3HuAeea/mAO+jgBrTfxlnG1zl3JyVYw96MeL7+/ZlEvqdJMGQloTX+SDfqit/og+sTATgQoBbrZptZ935HV+a0BDD2/p/Y/bZHnqMOpPZN+zTGlrOQcIr7Jd9RcHGsETFmvWgMEwEVUuGgppN5WvvgNrBI5Bi6OZ8kRs5GdYZvI+eBeF4/f6k74I21FTW8lfFhcUrbPMGJsCczQ+jMipvee11yRIho+JwkNUBz75kP/X76YS08S/LJ1SpOBI2t/4ztP4mTraAkeWe+ewE87TZooQ4TbKjPn56hOk/6JXW4vgfXuFgLBpsZVZamrJBpvNKDSdfz6ERutWgLhc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
